[package]
name = "ddc-flux"
version = "0.1.0"
authors = ["Billy J Rhoades II <me@brod.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3" }

chrono = "0.4"
sun-times = "0.1.2"

failure = "0.1.8"

ddc-i2c = { version = "0.2.1", features = ["with-linux-enumerate"] }
ddc = "0.2.2"
