[package]
name = "dlux"
version = "0.1.0"
authors = ["Billy J Rhoades II <me@brod.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3" }

tokio = { version = "0.3.2", features = ["macros", "net", "rt-multi-thread"] }

chrono = "0.4"
humantime = "2.0.1"
sun-times = "0.1.2"

failure = "0.1.8"

ddc-i2c = { version = "0.2.1", features = ["with-linux-enumerate"] }
i2c-linux = "0.1.2"
ddc = "0.2.2"

nix = "0.19.0"

